/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppPipelineRouteImport } from './routes/app.pipeline'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppIndicacoesRouteImport } from './routes/app.indicacoes'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppIaRouteImport } from './routes/app.ia'
import { Route as AppGanhosRouteImport } from './routes/app.ganhos'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppAtividadesRouteImport } from './routes/app.atividades'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminSuporteRouteImport } from './routes/admin.suporte'
import { Route as AdminParceriasRouteImport } from './routes/admin.parcerias'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminIndicacoesRouteImport } from './routes/admin.indicacoes'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'
import { Route as AdminImoveisRouteImport } from './routes/admin.imoveis'
import { Route as AdminIaRouteImport } from './routes/admin.ia'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AppParceriasIndexRouteImport } from './routes/app.parcerias.index'
import { Route as AppImoveisIndexRouteImport } from './routes/app.imoveis.index'
import { Route as AppParceriasAtivaRouteImport } from './routes/app.parcerias.ativa'
import { Route as AppParceriasIdRouteImport } from './routes/app.parcerias.$id'
import { Route as AppImoveisIdRouteImport } from './routes/app.imoveis.$id'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppIndicacoesRoute = AppIndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppGanhosRoute = AppGanhosRouteImport.update({
  id: '/ganhos',
  path: '/ganhos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAtividadesRoute = AppAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParceriasRoute = AdminParceriasRouteImport.update({
  id: '/parcerias',
  path: '/parcerias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIndicacoesRoute = AdminIndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImoveisRoute = AdminImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIaRoute = AdminIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AppParceriasIndexRoute = AppParceriasIndexRouteImport.update({
  id: '/parcerias/',
  path: '/parcerias/',
  getParentRoute: () => AppRoute,
} as any)
const AppImoveisIndexRoute = AppImoveisIndexRouteImport.update({
  id: '/imoveis/',
  path: '/imoveis/',
  getParentRoute: () => AppRoute,
} as any)
const AppParceriasAtivaRoute = AppParceriasAtivaRouteImport.update({
  id: '/parcerias/ativa',
  path: '/parcerias/ativa',
  getParentRoute: () => AppRoute,
} as any)
const AppParceriasIdRoute = AppParceriasIdRouteImport.update({
  id: '/parcerias/$id',
  path: '/parcerias/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppImoveisIdRoute = AppImoveisIdRouteImport.update({
  id: '/imoveis/$id',
  path: '/imoveis/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/imoveis': typeof AdminImoveisRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/indicacoes': typeof AdminIndicacoesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/parcerias': typeof AdminParceriasRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/atividades': typeof AppAtividadesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/ganhos': typeof AppGanhosRoute
  '/app/ia': typeof AppIaRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/indicacoes': typeof AppIndicacoesRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/imoveis/$id': typeof AppImoveisIdRoute
  '/app/parcerias/$id': typeof AppParceriasIdRoute
  '/app/parcerias/ativa': typeof AppParceriasAtivaRoute
  '/app/imoveis/': typeof AppImoveisIndexRoute
  '/app/parcerias/': typeof AppParceriasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/imoveis': typeof AdminImoveisRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/indicacoes': typeof AdminIndicacoesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/parcerias': typeof AdminParceriasRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/atividades': typeof AppAtividadesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/ganhos': typeof AppGanhosRoute
  '/app/ia': typeof AppIaRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/indicacoes': typeof AppIndicacoesRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/app/imoveis/$id': typeof AppImoveisIdRoute
  '/app/parcerias/$id': typeof AppParceriasIdRoute
  '/app/parcerias/ativa': typeof AppParceriasAtivaRoute
  '/app/imoveis': typeof AppImoveisIndexRoute
  '/app/parcerias': typeof AppParceriasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/imoveis': typeof AdminImoveisRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/indicacoes': typeof AdminIndicacoesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/parcerias': typeof AdminParceriasRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/atividades': typeof AppAtividadesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/ganhos': typeof AppGanhosRoute
  '/app/ia': typeof AppIaRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/indicacoes': typeof AppIndicacoesRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/imoveis/$id': typeof AppImoveisIdRoute
  '/app/parcerias/$id': typeof AppParceriasIdRoute
  '/app/parcerias/ativa': typeof AppParceriasAtivaRoute
  '/app/imoveis/': typeof AppImoveisIndexRoute
  '/app/parcerias/': typeof AppParceriasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/ia'
    | '/admin/imoveis'
    | '/admin/inbox'
    | '/admin/indicacoes'
    | '/admin/leads'
    | '/admin/parcerias'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/app/atividades'
    | '/app/configuracoes'
    | '/app/ganhos'
    | '/app/ia'
    | '/app/inbox'
    | '/app/indicacoes'
    | '/app/leads'
    | '/app/perfil'
    | '/app/pipeline'
    | '/admin/'
    | '/app/'
    | '/app/imoveis/$id'
    | '/app/parcerias/$id'
    | '/app/parcerias/ativa'
    | '/app/imoveis/'
    | '/app/parcerias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/ia'
    | '/admin/imoveis'
    | '/admin/inbox'
    | '/admin/indicacoes'
    | '/admin/leads'
    | '/admin/parcerias'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/app/atividades'
    | '/app/configuracoes'
    | '/app/ganhos'
    | '/app/ia'
    | '/app/inbox'
    | '/app/indicacoes'
    | '/app/leads'
    | '/app/perfil'
    | '/app/pipeline'
    | '/admin'
    | '/app'
    | '/app/imoveis/$id'
    | '/app/parcerias/$id'
    | '/app/parcerias/ativa'
    | '/app/imoveis'
    | '/app/parcerias'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/ia'
    | '/admin/imoveis'
    | '/admin/inbox'
    | '/admin/indicacoes'
    | '/admin/leads'
    | '/admin/parcerias'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/app/atividades'
    | '/app/configuracoes'
    | '/app/ganhos'
    | '/app/ia'
    | '/app/inbox'
    | '/app/indicacoes'
    | '/app/leads'
    | '/app/perfil'
    | '/app/pipeline'
    | '/admin/'
    | '/app/'
    | '/app/imoveis/$id'
    | '/app/parcerias/$id'
    | '/app/parcerias/ativa'
    | '/app/imoveis/'
    | '/app/parcerias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/pipeline': {
      id: '/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/indicacoes': {
      id: '/app/indicacoes'
      path: '/indicacoes'
      fullPath: '/app/indicacoes'
      preLoaderRoute: typeof AppIndicacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ia': {
      id: '/app/ia'
      path: '/ia'
      fullPath: '/app/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ganhos': {
      id: '/app/ganhos'
      path: '/ganhos'
      fullPath: '/app/ganhos'
      preLoaderRoute: typeof AppGanhosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/atividades': {
      id: '/app/atividades'
      path: '/atividades'
      fullPath: '/app/atividades'
      preLoaderRoute: typeof AppAtividadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parcerias': {
      id: '/admin/parcerias'
      path: '/parcerias'
      fullPath: '/admin/parcerias'
      preLoaderRoute: typeof AdminParceriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/indicacoes': {
      id: '/admin/indicacoes'
      path: '/indicacoes'
      fullPath: '/admin/indicacoes'
      preLoaderRoute: typeof AdminIndicacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/imoveis': {
      id: '/admin/imoveis'
      path: '/imoveis'
      fullPath: '/admin/imoveis'
      preLoaderRoute: typeof AdminImoveisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ia': {
      id: '/admin/ia'
      path: '/ia'
      fullPath: '/admin/ia'
      preLoaderRoute: typeof AdminIaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/parcerias/': {
      id: '/app/parcerias/'
      path: '/parcerias'
      fullPath: '/app/parcerias/'
      preLoaderRoute: typeof AppParceriasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/imoveis/': {
      id: '/app/imoveis/'
      path: '/imoveis'
      fullPath: '/app/imoveis/'
      preLoaderRoute: typeof AppImoveisIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parcerias/ativa': {
      id: '/app/parcerias/ativa'
      path: '/parcerias/ativa'
      fullPath: '/app/parcerias/ativa'
      preLoaderRoute: typeof AppParceriasAtivaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parcerias/$id': {
      id: '/app/parcerias/$id'
      path: '/parcerias/$id'
      fullPath: '/app/parcerias/$id'
      preLoaderRoute: typeof AppParceriasIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/imoveis/$id': {
      id: '/app/imoveis/$id'
      path: '/imoveis/$id'
      fullPath: '/app/imoveis/$id'
      preLoaderRoute: typeof AppImoveisIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminIaRoute: typeof AdminIaRoute
  AdminImoveisRoute: typeof AdminImoveisRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminIndicacoesRoute: typeof AdminIndicacoesRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminParceriasRoute: typeof AdminParceriasRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminIaRoute: AdminIaRoute,
  AdminImoveisRoute: AdminImoveisRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminIndicacoesRoute: AdminIndicacoesRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminParceriasRoute: AdminParceriasRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAtividadesRoute: typeof AppAtividadesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppGanhosRoute: typeof AppGanhosRoute
  AppIaRoute: typeof AppIaRoute
  AppInboxRoute: typeof AppInboxRoute
  AppIndicacoesRoute: typeof AppIndicacoesRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppIndexRoute: typeof AppIndexRoute
  AppImoveisIdRoute: typeof AppImoveisIdRoute
  AppParceriasIdRoute: typeof AppParceriasIdRoute
  AppParceriasAtivaRoute: typeof AppParceriasAtivaRoute
  AppImoveisIndexRoute: typeof AppImoveisIndexRoute
  AppParceriasIndexRoute: typeof AppParceriasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAtividadesRoute: AppAtividadesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppGanhosRoute: AppGanhosRoute,
  AppIaRoute: AppIaRoute,
  AppInboxRoute: AppInboxRoute,
  AppIndicacoesRoute: AppIndicacoesRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppIndexRoute: AppIndexRoute,
  AppImoveisIdRoute: AppImoveisIdRoute,
  AppParceriasIdRoute: AppParceriasIdRoute,
  AppParceriasAtivaRoute: AppParceriasAtivaRoute,
  AppImoveisIndexRoute: AppImoveisIndexRoute,
  AppParceriasIndexRoute: AppParceriasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
